//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenTaker
{
    using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD
    public partial class groupShare
    {
        public int id { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<int> folderId { get; set; }
        public Nullable<int> imageId { get; set; }
    
        public virtual folder folder { get; set; }
        public virtual personGroup personGroup { get; set; }
        public virtual image image { get; set; }
=======
    public partial class GroupShare
    {
        public int groupId { get; set; }
        public Nullable<int> folderId { get; set; }
        public Nullable<int> imageId { get; set; }
        public int id { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual PersonGroup PersonGroup { get; set; }
        public virtual Image Image { get; set; }
>>>>>>> hotfix
    }
}
